### ISSUE TITLE
(File.Error) could not stream "priv/static/assets/class.txt": no such file or directory

### ISSUE THREAD

**Issue by kianmeng** [maxmarcon/live_select#6]
Encountered when running test:

```sh
git clone https://github.com/maxmarcon/live_select.git
cd live_select
mix deps.get
mix test
...
..11:54:52.833 [error] Task #PID<0.1379.0> started from #PID<0.1378.0> terminating
** (File.Error) could not stream "priv/static/assets/class.txt": no such file or directory
    (elixir 1.14.0) lib/file/stream.ex:47: Collectable.File.Stream.into/1
    (elixir 1.14.0) lib/enum.ex:1499: Enum.into_protocol/2
    (elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<6.25363132/0 in LiveSelectWeb.ShowcaseLive.spawn_save_classes_task/2>
    Args: []

```

Did I miss out any steps?

**Comment by maxmarcon** [comment]
Thanks! Fixed with 34a9f79b32a9d00eddc4480b2730cf8e1d13105e
